spring.application.name=UploadAPI

# Azure Blob Storage configuration
spring.cloud.azure.storage.fileshare.enabled=false
spring.cloud.azure.storage.queue.enabled=false
spring.cloud.azure.storage.container-name=table28bills
spring.cloud.azure.storage.connection-string=BlobEndpoint=https://claimdocuments.blob.core.windows.net/;QueueEndpoint=https://claimdocuments.queue.core.windows.net/;FileEndpoint=https://claimdocuments.file.core.windows.net/;TableEndpoint=https://claimdocuments.table.core.windows.net/;SharedAccessSignature=sv=2024-11-04&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2025-11-02T17:21:47Z&st=2025-11-01T09:06:47Z&spr=https&sig=djbWsnfNhcAs%2F5%2B%2BYNZFEy75H0NyAmBTUPRqtPpnXhk%3D
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username= root
spring.datasource.password= root

# ===============================
# Hibernate / JPA
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none